export const HSN_CODES = [
  { hsn: '1001', description: 'Wheat', gstRate: 0 },
  { hsn: '1006', description: 'Rice', gstRate: 0 },
  { hsn: '0401', description: 'Milk and cream', gstRate: 0 },
  { hsn: '2106', description: 'Food preparations', gstRate: 18 },
  { hsn: '2201', description: 'Water (packaged)', gstRate: 12 },
  { hsn: '2202', description: 'Aerated drinks / soft drinks', gstRate: 28 },
  { hsn: '2402', description: 'Cigarettes / tobacco', gstRate: 28 },
  { hsn: '3004', description: 'Medicines / pharmaceuticals', gstRate: 12 },
  { hsn: '3301', description: 'Essential oils / perfumes', gstRate: 18 },
  { hsn: '3401', description: 'Soap / detergent', gstRate: 18 },
  { hsn: '3808', description: 'Insecticides / pesticides', gstRate: 18 },
  { hsn: '3923', description: 'Plastic packaging', gstRate: 18 },
  { hsn: '4011', description: 'Tyres (new)', gstRate: 28 },
  { hsn: '4901', description: 'Printed books', gstRate: 0 },
  { hsn: '4902', description: 'Newspapers / journals', gstRate: 0 },
  { hsn: '5201', description: 'Cotton (raw)', gstRate: 0 },
  { hsn: '5208', description: 'Cotton fabrics', gstRate: 5 },
  { hsn: '6101', description: 'Garments / clothing', gstRate: 12 },
  { hsn: '6403', description: 'Footwear', gstRate: 18 },
  { hsn: '7108', description: 'Gold', gstRate: 3 },
  { hsn: '7113', description: 'Jewellery', gstRate: 3 },
  { hsn: '8415', description: 'Air conditioners', gstRate: 28 },
  { hsn: '8418', description: 'Refrigerators', gstRate: 28 },
  { hsn: '8443', description: 'Printers', gstRate: 18 },
  { hsn: '8471', description: 'Computers / laptops', gstRate: 18 },
  { hsn: '8517', description: 'Mobile phones', gstRate: 18 },
  { hsn: '8703', description: 'Cars / automobiles', gstRate: 28 },
  { hsn: '8711', description: 'Motorcycles', gstRate: 28 },
  { hsn: '9403', description: 'Furniture', gstRate: 18 },
  { hsn: '9503', description: 'Toys', gstRate: 12 },
  // Services SAC codes
  { hsn: '9954', description: 'Construction services', gstRate: 18 },
  { hsn: '9961', description: 'Wholesale trade services', gstRate: 18 },
  { hsn: '9971', description: 'Financial services', gstRate: 18 },
  { hsn: '9972', description: 'Real estate services', gstRate: 18 },
  { hsn: '9973', description: 'Leasing / rental services', gstRate: 18 },
  { hsn: '9981', description: 'R&D services', gstRate: 18 },
  { hsn: '9982', description: 'Legal services', gstRate: 18 },
  { hsn: '9983', description: 'IT / software services', gstRate: 18 },
  { hsn: '9984', description: 'Telecom services', gstRate: 18 },
  { hsn: '9985', description: 'Support services', gstRate: 18 },
  { hsn: '9986', description: 'Agriculture support services', gstRate: 0 },
  { hsn: '9987', description: 'Maintenance / repair services', gstRate: 18 },
  { hsn: '9988', description: 'Manufacturing services', gstRate: 18 },
  { hsn: '9989', description: 'Food / beverage services', gstRate: 5 },
  { hsn: '9993', description: 'Health / education services', gstRate: 0 },
  { hsn: '9994', description: 'Sewage / waste services', gstRate: 18 },
  { hsn: '9995', description: 'Entertainment services', gstRate: 18 },
  { hsn: '9996', description: 'Cultural / sports services', gstRate: 18 },
  { hsn: '9997', description: 'Other personal services', gstRate: 18 },
]

export function searchHSN(query) {
  const q = query.toLowerCase()
  return HSN_CODES.filter(h =>
    h.hsn.includes(q) || h.description.toLowerCase().includes(q)
  ).slice(0, 8)
}